# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Get true branch name -- cannot rely on Build.SourceBranchName
name: $[ variables['branchName'] ]
variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    branchName: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    branchName: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]

trigger:
  branches:
    include:
    - 'release/*'

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0
  fetchTags: true
  persistCredentials: true

- script: |
    git config user.email pipeline@pipeline.com & git config user.name "Pipeline"
  displayName: Set Git username and email for pipeline
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: |
    versionNumber="$(git show -s --format=%s)"
    git checkout production
    git merge --no-ff "$BUILD_SOURCEBRANCH"
  displayName: Commit incremented version
  workingDirectory: $(System.DefaultWorkingDirectory)
