# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - 'release/*'

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- script: |
    git config user.email pipeline@pipeline.com & git config user.name "Pipeline"
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: |
    git checkout origin/production
  workingDirectory: $(System.DefaultWorkingDirectory)
